import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3'
import { getPresetById, isProxyPreset } from '../../utils/presets'
import type { ProxyCredentials } from '../../../app/types/connection'

// Type for AWS SDK stream body that can be transformed to web stream
interface SdkStreamBody {
  transformToWebStream?: () => ReadableStream
}

// =============================================================================
// OBJECT ACCESS TOKEN CACHE
// =============================================================================

interface ObjectAccessToken {
  /** Preset ID (for preset-based proxy) */
  presetId?: string
  /** Direct credentials (for saved connections with useProxy) */
  credentials?: ProxyCredentials
  /** Target bucket */
  bucket: string
  /** Object key */
  key: string
  /** Token expiration timestamp */
  expiresAt: number
}

// In-memory token cache - tokens are short-lived (default 1 hour)
const tokenCache = new Map<string, ObjectAccessToken>()

// Cleanup expired tokens periodically
const CLEANUP_INTERVAL = 60 * 1000 // 1 minute
let cleanupTimer: ReturnType<typeof setInterval> | null = null

function startTokenCleanup() {
  if (cleanupTimer) return
  cleanupTimer = setInterval(() => {
    const now = Date.now()
    for (const [token, data] of tokenCache.entries()) {
      if (data.expiresAt < now) {
        tokenCache.delete(token)
      }
    }
  }, CLEANUP_INTERVAL)
}

// Start cleanup on module load
startTokenCleanup()

/**
 * Generate a secure random token
 */
function generateToken(): string {
  const array = new Uint8Array(32)
  crypto.getRandomValues(array)
  return Array.from(array, (b) => b.toString(16).padStart(2, '0')).join('')
}

/**
 * Create an object access token and return the proxy URL
 */
export function createObjectProxyUrl(
  options: {
    presetId?: string
    credentials?: ProxyCredentials
    bucket: string
    key: string
    expiresIn?: number // in seconds, default 3600
  }
): string {
  const { presetId, credentials, bucket, key, expiresIn = 3600 } = options

  const token = generateToken()
  const expiresAt = Date.now() + expiresIn * 1000

  tokenCache.set(token, {
    presetId,
    credentials,
    bucket,
    key,
    expiresAt,
  })

  // Return relative URL - will work regardless of host
  return `/api/proxy/object?token=${token}`
}

/**
 * Validate a token and return the access data
 */
function validateToken(token: string): ObjectAccessToken | null {
  const data = tokenCache.get(token)
  if (!data) return null
  if (data.expiresAt < Date.now()) {
    tokenCache.delete(token)
    return null
  }
  return data
}

// =============================================================================
// S3 CLIENT HELPERS
// =============================================================================

function getS3ClientForPreset(presetId: string): S3Client | null {
  const preset = getPresetById(presetId)
  if (!preset || !preset.accessKey || !preset.secretKey) {
    return null
  }

  return new S3Client({
    endpoint: preset.endpoint,
    region: preset.region,
    forcePathStyle: preset.pathStyle,
    credentials: {
      accessKeyId: preset.accessKey,
      secretAccessKey: preset.secretKey,
    },
  })
}

function createS3ClientFromCredentials(credentials: ProxyCredentials): S3Client {
  return new S3Client({
    endpoint: credentials.endpoint,
    region: credentials.region,
    forcePathStyle: credentials.pathStyle,
    credentials: {
      accessKeyId: credentials.accessKey,
      secretAccessKey: credentials.secretKey,
    },
  })
}

// =============================================================================
// MAIN HANDLER
// =============================================================================

/**
 * GET /api/proxy/object
 *
 * Streams object data through the proxy, bypassing the need for presigned URLs
 * that point to internal/unreachable endpoints.
 *
 * Query parameters:
 * - token: Access token (generated by createObjectProxyUrl)
 */
export default defineEventHandler(async (event) => {
  const query = getQuery(event)
  const token = query['token'] as string | undefined

  if (!token) {
    throw createError({
      statusCode: 400,
      message: 'Missing required parameter: token',
    })
  }

  // Validate token
  const accessData = validateToken(token)
  if (!accessData) {
    throw createError({
      statusCode: 401,
      message: 'Invalid or expired token',
    })
  }

  const { presetId, credentials, bucket, key } = accessData

  // Get S3 client
  let client: S3Client | null = null
  let shouldDestroyClient = false

  if (presetId) {
    if (!isProxyPreset(presetId)) {
      throw createError({
        statusCode: 403,
        message: 'Preset not found or not proxy-enabled',
      })
    }
    client = getS3ClientForPreset(presetId)
  } else if (credentials) {
    client = createS3ClientFromCredentials(credentials)
    shouldDestroyClient = true
  }

  if (!client) {
    throw createError({
      statusCode: 500,
      message: 'Failed to create S3 client',
    })
  }

  // Fetch the object
  try {
    const response = await client.send(
      new GetObjectCommand({
        Bucket: bucket,
        Key: key,
      })
    )

    // Set appropriate headers
    const headers: Record<string, string> = {}

    if (response.ContentType) {
      headers['Content-Type'] = response.ContentType
    }
    if (response.ContentLength !== undefined) {
      headers['Content-Length'] = String(response.ContentLength)
    }
    if (response.ETag) {
      headers['ETag'] = response.ETag
    }
    if (response.LastModified) {
      headers['Last-Modified'] = response.LastModified.toUTCString()
    }
    // Cache for 1 hour since tokens are already short-lived
    headers['Cache-Control'] = 'private, max-age=3600'

    // Set headers on the response
    for (const [name, value] of Object.entries(headers)) {
      setHeader(event, name, value)
    }

    // Stream the body
    if (response.Body) {
      // AWS SDK v3 returns SdkStream which can be transformed to various stream types
      const sdkStream = response.Body as SdkStreamBody

      // Use web stream for better compatibility
      if (typeof sdkStream.transformToWebStream === 'function') {
        const webStream = sdkStream.transformToWebStream()
        // h3's sendStream accepts both Node.js streams and Web ReadableStreams
        return sendStream(event, webStream).finally(() => {
          if (shouldDestroyClient) client?.destroy()
        })
      }

      // Fallback: use response.Body directly if it's already streamable
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const streamBody = response.Body as any
      if (shouldDestroyClient) {
        streamBody.on?.('end', () => client?.destroy())
        streamBody.on?.('error', () => client?.destroy())
      }
      return sendStream(event, streamBody)
    }

    if (shouldDestroyClient) client.destroy()
    return null
  } catch (error) {
    if (shouldDestroyClient) client.destroy()

    const err = error as Error & { Code?: string; $metadata?: { httpStatusCode?: number } }
    const statusCode = err.$metadata?.httpStatusCode || 500

    throw createError({
      statusCode,
      message: err.Code || err.message || 'Failed to fetch object',
    })
  }
})
